version: '3'
services:
  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=linuxcli
      - MYSQL_PASSWORD=linuxcli
      - MYSQL_DATABASE=linuxcli
